version: 0.2

phases:

  pre_build:

    commands:

      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - REPOSITORY_URI=877278458853.dkr.ecr.ap-northeast-1.amazonaws.com/koub-ecr
      - TAG="dev-c"

  build:

    commands:

    - docker build -t $REPOSITORY_URI:$TAG .
    - docker tag $REPOSITORY_URI:$TAG $REPOSITORY_URI:$TAG

  post_build:

    commands:

    - docker push $REPOSITORY_URI:$TAG
    - printf '[{"name":"koub-c-container","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > image.json

artifacts:

  files: image.json
